# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Signup.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5.QtWidgets import QMessageBox 
from PyQt5 import QtCore, QtGui, QtWidgets
import sqlite3
import sys

class Ui_MainWindow(object):
    def __init__(self):
        
        self.mainwindow = QtWidgets.QWidget()
        
        self.setupUi()
        
    def show(self):
        self.mainwindow.show()

    def setupUi(self):
        self.mainwindow.setObjectName("MainWindow")
        self.mainwindow.resize(305, 539)
        
        
        self.groupBox = QtWidgets.QGroupBox(self.mainwindow)
        self.groupBox.setGeometry(QtCore.QRect(30, 50, 261, 381))
        self.groupBox.setStyleSheet("background:Gray;")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit.setGeometry(QtCore.QRect(120, 70, 113, 21))
        self.lineEdit.setStyleSheet("background:White;")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_2.setGeometry(QtCore.QRect(120, 110, 113, 21))
        self.lineEdit_2.setStyleSheet("background:White;")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_3.setGeometry(QtCore.QRect(120, 150, 113, 21))
        self.lineEdit_3.setStyleSheet("background:White;")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 70, 81, 21))
        self.label.setStyleSheet("color:white;\n"
"border: 2px solid red;\n"
"")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(10, 110, 81, 21))
        self.label_2.setStyleSheet("color:white;\n"
"border: 2px solid red;\n"
"")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(10, 150, 81, 21))
        self.label_3.setStyleSheet("color:white;\n"
"border: 2px solid red;\n"
"")
        self.label_3.setObjectName("label_3")
        self.pushButton = QtWidgets.QPushButton(self.groupBox)
        self.pushButton.setGeometry(QtCore.QRect(70, 310, 93, 28))
        self.pushButton.setStyleSheet("background:light grey;\n"
"color:white;\n"
"border: 2px solid black")
        self.pushButton.setObjectName("pushButton")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_4.setGeometry(QtCore.QRect(120, 190, 113, 21))
        self.lineEdit_4.setStyleSheet("background:White;")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_5.setGeometry(QtCore.QRect(120, 230, 113, 21))
        self.lineEdit_5.setStyleSheet("background:White;")
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_6.setGeometry(QtCore.QRect(120, 270, 113, 21))
        self.lineEdit_6.setStyleSheet("background:White;")
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(10, 190, 81, 21))
        self.label_4.setStyleSheet("color:white;\n"
"border: 2px solid red;\n"
"")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(10, 230, 81, 21))
        self.label_5.setStyleSheet("color:white;\n"
"border: 2px solid red;\n"
"")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(10, 270, 81, 21))
        self.label_6.setStyleSheet("color:white;\n"
"border: 2px solid red;\n"
"")
        self.label_6.setObjectName("label_6")
        
        self.menubar = QtWidgets.QMenuBar(self.mainwindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 305, 26))
        self.menubar.setObjectName("menubar")
      
        self.statusbar = QtWidgets.QStatusBar(self.mainwindow)
        self.statusbar.setObjectName("statusbar")
      

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self.mainwindow)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.mainwindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "아이디"))
        self.label_2.setText(_translate("MainWindow", "비밀번호"))
        self.label_3.setText(_translate("MainWindow", "비번확인"))
        self.pushButton.setText(_translate("MainWindow", "계정 생성"))
        self.label_4.setText(_translate("MainWindow", "이름"))
        self.label_5.setText(_translate("MainWindow", "이메일"))
        self.label_6.setText(_translate("MainWindow", "전화번호"))
        self.pushButton.clicked.connect(self.signup)
    
    def signup(self):
        self.conn=sqlite3.connect('userdata.db')
        self.cur=self.conn.cursor()
        self.id=self.lineEdit.text()
        self.pw=self.lineEdit_2.text()
        self.checkpw=self.lineEdit_3.text()
        self.name=self.lineEdit_4.text()
        self.email=self.lineEdit_5.text()
        self.phonenumber=self.lineEdit_6.text()
        self.cur.execute("DROP TABLE user")
        self.cur.execute("CREATE TABLE user (id TEXT,password TEXT,name TEXT,email TEXT,phonenumber TEXT,win TEXT, lose TEXT, winrate TEXT)")
        if self.pw!=self.checkpw:
            QtWidgets.QMessageBox.warning(self.mainwindow, "Warning", "비밀번호가 틀렸습니다")
            self.lineEdit_2.setText(None)
            self.lineEdit_3.setText(None)
        else:
            QtWidgets.QMessageBox.information(self.mainwindow, "계정 생성", "계정 생성 완료!")
            self.cur.execute("INSERT INTO user VALUES('"+self.id+"','"+self.pw+"','"+self.name+"','"+self.email+"','"+self.phonenumber+"','0','0','0')")
            self.conn.commit()
            self.conn.close()
if __name__ == "__main__":
 
    app = QtWidgets.QApplication(sys.argv)
    asdf=Ui_MainWindow()
    asdf.show()
    sys.exit(app.exec_())
